version: '3.8'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "2828:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  mysql_data:
